# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 14:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': '\u0434\u043e\u0445\u043e\u0434', 'verbose_name_plural': '\u0434\u043e\u0445\u043e\u0434\u044b'},
        ),
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 15, 14, 1, 40, 82590, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(default='Salary', max_length=100),
        ),
    ]
