# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '\u043f\u0440\u043e\u0444\u0438\u043b\u044c', 'verbose_name_plural': '\u043f\u0440\u043e\u0444\u0438\u043b\u0438'},
        ),
    ]
