# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(default=0, verbose_name='\u0427\u0430\u0441\u0442\u043e\u0442\u0430')),
                ('category', models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='\u0421\u043e\u0432\u0435\u0442')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u0441\u043e\u0432\u0435\u0442',
                'verbose_name_plural': '\u0441\u043e\u0432\u0435\u0442\u044b',
            },
        ),
    ]
