# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
