# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('I', 'Income'), ('E', 'Expenses')], max_length=20, null=True),
        ),
    ]
